name: Dependency Updates

on:
  schedule:
    - cron: '0 6 * * 1' # Run every Monday at 6 AM UTC
  workflow_dispatch: # Allow manual triggering

jobs:
  update-dependencies:
    name: Update dependencies
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Update dependencies
        id: update
        run: |
          npm install -g npm-check-updates
          ncu -u
          npm install
          
          if [[ -n $(git status --porcelain) ]]; then
            echo "updates_available=true" >> $GITHUB_OUTPUT
          else
            echo "updates_available=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Create Pull Request
        if: steps.update.outputs.updates_available == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore(deps): update dependencies'
          title: '🔄 Update dependencies'
          body: |
            This PR updates project dependencies to their latest versions.
            
            **Automated changes by the dependency update workflow**
            
            Before merging, please verify that all tests pass and the application still works as expected.
          branch: dependencies/update
          base: main
          labels: dependencies